CREATE TABLE #MOSTLY_BUDGET_COST
(
YEAR_YYYY INT,
MONTH_YYYYMM INT,
REGION VARCHAR(100),
DEPARTMENT VARCHAR(100),
BUDGET_COST INT
)

INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202001,'AFRICA','IT',1000)
INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202001,'USA','TECH CS',3000)
INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202001,'ASIA','SALES',2000)
INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202001,'EUROPE','IT',1800)
INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202002,'AFRICA','IT',1000)
INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202002,'USA','TECH CS',3000)
INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202002,'ASIA','SALES',2000)
INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202002,'EUROPE','IT',1800)
INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202003,'AFRICA','IT',1000)
INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202003,'USA','TECH CS',3000)
INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202003,'ASIA','SALES',2000)
INSERT INTO #MOSTLY_BUDGET_COST VALUES (2020,202003,'EUROPE','IT',1800)

CREATE TABLE #REGION
(
REGION VARCHAR(100),
COUNTRY VARCHAR(100),
REGIONAL_MANAGER VARCHAR (100)
)

INSERT INTO #REGION VALUES ('USA','NORTHE USA','A1')
INSERT INTO #REGION VALUES ('USA','SOUTH USA','A2')
INSERT INTO #REGION VALUES ('AFRICA','NORTHE AFRICA','B1')
INSERT INTO #REGION VALUES ('AFRICA','SOUTH AFRICA','B2')
INSERT INTO #REGION VALUES ('ASIA','INDIA','C1')
INSERT INTO #REGION VALUES ('ASIA','CHINA','C2')
INSERT INTO #REGION VALUES ('ASIA','JAPAN','C3')
INSERT INTO #REGION VALUES ('EUROPE','LONDON','D1')



CREATE TABLE #DEPARTMENT
(
DEPARTMENT VARCHAR(100),
REGION VARCHAR(100),
DEPARTMENT_MANAGER VARCHAR (100)
)

INSERT INTO #DEPARTMENT VALUES ('IT','ASIA','XX1')
INSERT INTO #DEPARTMENT VALUES ('SALES','AFRICA','YY1')
INSERT INTO #DEPARTMENT VALUES ('PRODUCTION',' USA','ZZ1')
INSERT INTO #DEPARTMENT VALUES ('FINANCE','EUROPE','LL1')

CREATE TABLE #DAILYSALES
(
DEPARTMENT VARCHAR(100),
SALES_DATE_YYYYMMDD VARCHAR(100),
SALES_GROSS FLOAT,
SALES_TAX_AMMOUNT FLOAT
)

INSERT INTO #DAILYSALES VALUES ('IT','20200115',1000,150)
INSERT INTO #DAILYSALES VALUES ('IT','20201215',150,225)
INSERT INTO #DAILYSALES VALUES ('SALES','20200131',2000,200)
INSERT INTO #DAILYSALES VALUES ('SALES','20201231',1000,150)
INSERT INTO #DAILYSALES VALUES ('PRODUCTION','20200131',5000,400)
INSERT INTO #DAILYSALES VALUES ('PRODUCTION','20201231',2000,200)
INSERT INTO #DAILYSALES VALUES ('FINANCE','20200130',1000,150)
---------------------------------------------------
CREATE TABLE #YEARLY_SALES_BY_COUNTRY
(
COUNTRY VARCHAR(100),
YEAR_YYYY VARCHAR(100),
SALES_NET_AMOUNT FLOAT,
SALES_TAX_AMMOUNT FLOAT
)


SELECT
R.COUNTRY,
YEAR_YYYY=YEAR(DS.SALES_DATE_YYYYMMDD),
SALES_NET_AMOUNT=SUM(SALES_GROSS-SALES_TAX_AMMOUNT),
SALES_TAX_AMMOUNT=SUM(SALES_TAX_AMMOUNT)
FROM
#REGION R
 JOIN #DEPARTMENT D ON R.REGION=D.REGION
 JOIN #DAILYSALES DS ON D.DEPARTMENT=DS.DEPARTMENT
GROUP BY R.COUNTRY,YEAR(DS.SALES_DATE_YYYYMMDD)


CREATE TABLE #MONTLY_PROFIT_BY_DEPARTMENT
(
MONTH_YYYYMM VARCHAR(10),
COUNTRY VARCHAR(10),
DEPARTMENT VARCHAR(10),
DEPARTMENT_MANAGER VARCHAR (10),
BUDGET_COST FLOAT,
SALES_NET_AMMOUNT FLOAT,
PROFIT FLOAT
)

SELECT
B.MONTH_YYYYMM
,R.COUNTRY
,D.DEPARTMENT
,D.DEPARTMENT_MANAGER
,SUM(B.BUDGET_COST) as BUDGET_COST
,SALES_NET_AMOUNT=SUM(SALES_GROSS-SALES_TAX_AMMOUNT)
,PROFIT = (SUM(SALES_GROSS-SALES_TAX_AMMOUNT) - BUDGET_COST)
FROM
#MOSTLY_BUDGET_COST B
JOIN #REGION R ON R.REGION=B.REGION
 JOIN #DEPARTMENT D ON R.REGION=D.REGION
 JOIN #DAILYSALES DS ON D.DEPARTMENT=DS.DEPARTMENT
GROUP BY
B.MONTH_YYYYMM
,R.COUNTRY
,D.DEPARTMENT
,D.DEPARTMENT_MANAGER